### ISSUE TITLE
incompatible with terraform-labels 0.14.0

### ISSUE THREAD

**Issue by neermitt** [clouddrove/terraform-aws-route53#5]
version used: 0.12.1

Error: Unsupported argument

  on .terraform/modules/mail_dns_records/main.tf line 12, in module "labels":
  12:   application = var.application

An argument named "application" is not expected here.

**Comment by mrcomoraes** [comment]
Same problem here

Terraform v0.13.6

**Comment by sohanyadav** [comment]
@neermitt  @mrcomoraes:   we removed the  `application` From tag 0.14, see the  [labels] (https://github.com/clouddrove/terraform-aws-labels)  modue

This is not a bug so I'm going to close this ticket.
